---

version: '3.3'

services:

  # gateway:
  #   image: test-gateway
  #   build:
  #     context: gateway
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   entrypoint: uvicorn gateway:app --host 0.0.0.0 --port 8000
  #   ports:
  #     - 8000:8000

  frontend:
    image: test-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    entrypoint: flask run --host 0.0.0.0 --port 8000
    ports:
      - "9001-9010:8000"
    scale: 4


...
